# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0'

target 'ydisk_skillbox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ydisk_skillbox

  target 'ydisk_skillboxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ydisk_skillboxUITests' do
    # Pods for testing
  end

pod 'YandexLoginSDK'
pod 'Alamofire'


end
